baseURL: "https://genmun.github.io/"
languageCode: en-us
title: GMUN
menu:
  main:
    - identifier: about
      name: About
      weight: 1
    - identifier: conference
      name: Conference
      weight: 2
    - identifier: schedule
      name: Schedule
      url: /schedule
      parent: conference
      weight: 1
    - identifier: registration
      name: Registration
      weight: 3
    - identifier: councils
      name: Councils
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact
      parent: about
      weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
