baseURL: "https://gmun.my/"
languageCode: en-us
title: GMUN
timeZone: Local
menu:
  main:
    - identifier: about
      name: About
      weight: 1
    - identifier: about-us
      name: About Us
      url: /about
      parent: about
      weight: 1
    - identifier: team
      name: Meet The Team
      url: /team
      parent: about
      weight: 2
    - identifier: venue
      name: Venue
      url: /venue
      parent: about
      weight: 3
    - identifier: contact
      name: Contact us
      url: /contact
      parent: about
      weight: 4
    - identifier: conference
      name: Conference
      weight: 2
    - identifier: faq
      name: FAQ
      url: /faq
      parent: conference
      weight: 1
    - identifier: schedule
      name: Schedule
      url: /schedule
      parent: conference
      weight: 2
    - identifier: registration
      name: Registration
      url: /registration
      weight: 3
    - identifier: councils
      name: Councils
      url: /councils
      weight: 4
markup:
  goldmark:
    renderer:
      unsafe: true
